[package]
name = "cat-bot"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/Ang2Tea/cat-bot"
readme = "README.md"

[[bin]]
name = "cat-bot"
path = "src/bin/shuttle/main.rs"

[[bin]]
name = "standalone"
path = "src/bin/standalone/main.rs"

[dependencies]
tracing = { workspace = true }

# Telegram API
teloxide = { version = "0.17.0", features = ["macros"] }
reqwest = { version = "0.12.19", features = ["json", "blocking"] }

cat-core = { path = "../cat-core" }
cat-sqlx-repo = { path = "../cat-sqlx-repo", features = ["postgres"] }
cat-diesel-repo = { path = "../cat-diesel-repo", features = ["postgres"] }
cat-adapters = { path = "../cat-adapters" }

sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres"] }

shuttle-runtime = { version = "0.57.0", features = ["tracing-subscriber"] }
shuttle-shared-db = { version = "0.57.0", features = ["postgres", "sqlx"] }

tokio = { workspace = true }
dotenvy = "0.15.7"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
