[package]
name = "cat-bot-databases"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/Ang2Tea/cat-bot"
readme = "README.md"

[features]
default = []
sqlx = ["dep:sqlx"]
diesel = ["dep:diesel", "dep:diesel-async", "diesel-async/bb8"]
postgres = ["diesel-async/postgres", "sqlx/postgres"]

[dependencies]
tokio = { workspace = true }

sqlx = { version = "0.8.6", optional = true, features = ["runtime-tokio"] }
diesel = { version = "2.2.12", optional = true }
diesel-async = { version = "0.6.1", optional = true }

cat-bot-entities = { path = "../cat-bot-entities" }
