[package]
name = "cat-bot-standalone"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/Ang2Tea/cat-bot"
readme = "README.md"

[dependencies]
cat-bot={path = "../cat-bot"}

tokio = { workspace = true }

dotenvy = "0.15.7"

tracing = { workspace = true }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }